version: '3.7'

services:
  demo:
    image: dsdebayan/eauction:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - eauction-network

networks:
  eauction-network:      
      

      